# Generated by Django 5.0.1 on 2025-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('velocidad_bajada', models.IntegerField(help_text='Mbps')),
                ('velocidad_subida', models.IntegerField(help_text='Mbps')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Servicio',
                'verbose_name_plural': 'Planes de Servicio',
                'db_table': 'planes',
            },
        ),
    ]
