# Generated by Django 5.0.1 on 2025-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='datos_respuesta',
            field=models.JSONField(blank=True, help_text='Respuesta completa del gateway', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='ID de transacción de Wompi/PayU', max_length=200),
        ),
    ]
