# Generated by Django 5.0.1 on 2025-12-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
        ('pagos', '0002_pago_datos_respuesta_pago_referencia_externa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago']},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='datos_respuesta',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='referencia_externa',
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('wompi_card', 'Tarjeta de Crédito/Débito (Wompi)'), ('wompi_pse', 'PSE (Wompi)'), ('wompi_nequi', 'Nequi (Wompi)'), ('wompi_bancolombia', 'Transferencia Bancolombia (Wompi)'), ('transferencia_bancaria', 'Transferencia Bancaria Manual'), ('efectivo', 'Efectivo')], default='transferencia_bancaria', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_transaccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='wompi_payment_method_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='wompi_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='wompi_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='wompi_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturas.factura'),
        ),
        migrations.AlterModelTable(
            name='pago',
            table=None,
        ),
    ]
