# Generated by Django 5.0.1 on 2025-12-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_codigoverificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Usuario bloqueado por comportamiento inadecuado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_bloqueo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_bloqueo',
            field=models.TextField(blank=True, help_text='Razón del bloqueo', null=True),
        ),
    ]
