# Generated by Django 5.0.1 on 2026-01-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='motivo_suspension',
            field=models.TextField(blank=True, null=True),
        ),
    ]
