# Generated by Django 5.0.1 on 2025-12-01 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-creado'], 'verbose_name': 'Ticket de Soporte', 'verbose_name_plural': 'Tickets de Soporte'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='datos_adicionales',
            field=models.JSONField(blank=True, help_text='Datos específicos del tipo de ticket', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('problema_conexion', 'Problema de Conexión'), ('traslado', 'Traslado de Servicio'), ('router_adicional', 'Router Adicional'), ('cambio_plan', 'Cambio de Plan'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('es_interno', models.BooleanField(default=False, help_text='Comentario solo visible para personal')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentarios_ticket',
                'ordering': ['creado'],
            },
        ),
    ]
